# =========================================================
# DEVELOPMENT-ONLY CONFIGURATION
# Overrides application.yml when profile = dev
# =========================================================

# -------------------------------------------------------
# SPRING CONFIGURATION (DEV OVERRIDES)
# -------------------------------------------------------
spring:

  # -----------------------------------------------------
  # JACKSON (JSON SERIALIZATION CONFIG)
  # -----------------------------------------------------
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      read-date-timestamps-as-nanoseconds: true
    time-zone: UTC

# -------------------------------------------------------
# SERVER CONFIG
# -------------------------------------------------------
server:
  port: ${PORT:8084}

security:
  auth:
    enabled: true

jwt:
  accessSecret: asdfsdfarwegrsKLSAHAKBIUUIBuseweDOIy8b_)@#r43243234sadfew23fsxcasdfq32refwasegsade234ew
  access-token:
    expiration-ms: 900000
  refresh-token:
    expiration-ms: 2592000000
