package realtime_gateway.infrastructure.messaging.kafka.consumer

import com.xapps.messaging.kafka.KafkaTopics
import com.xapps.messaging.kafka.events.ClassroomQuizDeliveredEvent
import com.xapps.platform.core.compression.ObjectCompressionService
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import org.slf4j.LoggerFactory
import org.springframework.kafka.annotation.KafkaListener
import org.springframework.stereotype.Component
import realtime_gateway.infrastructure.messaging.kafka.config.KafkaBroadcastConsumerConfig
import realtime_gateway.infrastructure.messaging.websocket.model.ServerWebSocketMessage
import realtime_gateway.infrastructure.messaging.websocket.outgoing_message.OutgoingWebSocketMessageService

/**
 * Kafka consumer responsible for handling classroom quiz delivery events and notifying tutors in real time.
 *
 * <p>
 * This component listens for {@link ClassroomQuizDeliveredEvent} messages, which indicate that a previously
 * requested classroom quiz has been successfully generated by the quiz service.
 *
 * <p>
 * Upon receiving such an event, this consumer:
 * 1. Extracts the tutor identifier and generated quiz IDs from the event payload.
 * 2. Sends a WebSocket message to the tutor notifying them that the quiz is ready.
 *
 * <p>
 * The tutor receives only a list of quiz IDs, which are intended to be used to fetch the full quiz data
 * directly from the classroom quiz service via a subsequent GET request.
 *
 * <p>
 * This class strictly acts as a translation layer between Kafka event ingestion and WebSocket-based
 * real-time delivery to connected tutors.
 */
@Component
class TutorQuizGenerationNotificationConsumer(
    private val outgoingWebSocketMessageService: OutgoingWebSocketMessageService,
    private val compressionService: ObjectCompressionService
) {

    private val log = LoggerFactory.getLogger(javaClass)

    /**
     * Handles incoming Kafka messages indicating that a classroom quiz has been generated.
     *
     * <p>
     * This method:
     * - Deserializes the incoming JSON payload into a {@link ClassroomQuizDeliveredEvent}.
     * - Asynchronously dispatches a WebSocket notification to the target tutor.
     *
     * @param rawEventPayload JSON string representing the {@link ClassroomQuizDeliveredEvent}.
     */
    @KafkaListener(
        topics = [KafkaTopics.Quiz.CLASSROOM_PAYLOAD],
        containerFactory = KafkaBroadcastConsumerConfig.BROADCAST_KAFKA_LISTENER_CONTAINER_FACTORY
    )
    fun handleClassroomQuizGeneratedEvent(payload: ByteArray) {

        log.info("Received ClassroomQuizDeliveredEvent: $payload")

        val classroomQuizDeliveredEvent = compressionService.decompress(
            ClassroomQuizDeliveredEvent.serializer(),
            payload
        )

        CoroutineScope(Dispatchers.IO).launch {
            notifyTutorQuizIsReady(classroomQuizDeliveredEvent)
        }
    }

    /**
     * Sends a real-time WebSocket notification to the tutor indicating that their requested
     * classroom quiz has been generated and is ready for retrieval.
     *
     * <p>
     * The notification payload contains only quiz IDs. The tutor is expected to use these IDs
     * to fetch full quiz details from the classroom quiz service.
     *
     * @param event the domain event containing tutor ID and generated quiz IDs.
     */
    private suspend fun notifyTutorQuizIsReady(event: ClassroomQuizDeliveredEvent) {
        outgoingWebSocketMessageService.sendToUser(
            userId = event.tutorId,
            payload = ServerWebSocketMessage.NewClassroomQuizPayload(event.quizIds)
        )
    }
}